apiVersion: v1
kind: Service
metadata:
  name: cviche-backend-svc
spec:
  selector:
    app: cviche-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP                