"""add auth_method column to users

Revision ID: 1b8fabfe276a
Revises: aa2804eccc17
Create Date: 2026-03-24 22:05:01.340507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8fabfe276a'
down_revision: Union[str, Sequence[str], None] = 'aa2804eccc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_method', sa.String(length=20), server_default='simple', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_method')
    # ### end Alembic commands ###
