"""add hot column indexes

Adds indexes on the hot filter/sort columns and the run_id foreign keys that
lacked explicit indexes. runs.status and runs.started_at back the admin
dashboard's status filter and started_at ordering; steps/logs/llm_usage.run_id
back the per-run joins. InnoDB already auto-indexes FK columns, so on MySQL the
run_id indexes are largely redundant but harmless and keep the schema explicit
and consistent with SQLite (which does NOT auto-index FKs).

Index names match those auto-generated by Base.metadata.create_all for fresh
installs (ix_<table>_<column>), so the migrated and create_all schemas converge;
all are well under MySQL's 64-char identifier limit. Adding/dropping an index
needs no batch_alter_table on SQLite, so plain op.create_index/op.drop_index is
valid on both SQLite and MySQL/MariaDB.

Revision ID: 5a74eb0f9645
Revises: f1a2b3c4d5e6
Create Date: 2026-06-04
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a74eb0f9645'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index('ix_runs_status', 'runs', ['status'], unique=False)
    op.create_index('ix_runs_started_at', 'runs', ['started_at'], unique=False)
    op.create_index('ix_steps_run_id', 'steps', ['run_id'], unique=False)
    op.create_index('ix_logs_run_id', 'logs', ['run_id'], unique=False)
    op.create_index('ix_llm_usage_run_id', 'llm_usage', ['run_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_llm_usage_run_id', table_name='llm_usage')
    op.drop_index('ix_logs_run_id', table_name='logs')
    op.drop_index('ix_steps_run_id', table_name='steps')
    op.drop_index('ix_runs_started_at', table_name='runs')
    op.drop_index('ix_runs_status', table_name='runs')
