"""add research data capture tables

Revision ID: aa2804eccc17
Revises: b3f7e2a1c804
Create Date: 2026-03-20 16:04:19.571799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2804eccc17'
down_revision: Union[str, Sequence[str], None] = 'b3f7e2a1c804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage', sa.Column('model_version', sa.String(length=100), nullable=True))
    op.add_column('llm_usage', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('llm_usage', sa.Column('finish_reason', sa.String(length=50), nullable=True))
    op.add_column('llm_usage', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('llm_usage', sa.Column('prompt_version', sa.String(length=64), nullable=True))
    op.add_column('steps', sa.Column('error_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'error_type')
    op.drop_column('llm_usage', 'prompt_version')
    op.drop_column('llm_usage', 'retry_count')
    op.drop_column('llm_usage', 'finish_reason')
    op.drop_column('llm_usage', 'temperature')
    op.drop_column('llm_usage', 'model_version')
    # ### end Alembic commands ###
