apiVersion: v1
kind: Service
metadata:
  name: cviche-frontend-svc
spec:
  selector:
    app: cviche-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # nginx's unprivileged port (#109)