apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pointing directly to the files since base has no index
resources:
 - ../../base  # Point to the FOLDER, not the files inside it

namespace: cviche-dev

configMapGenerator:
  - name: cviche-config
    literals:
      - DB_URL: "<DB_URL_PLACEHOLDER>"
      - LOG_LEVEL: "<LOG_LEVEL_PLACEHOLDER>"

secretGenerator:
  - name: cviche-secrets
    type: Opaque
    literals:
      - DB_PASSWORD: "VAR_DB_PASSWORD"
      - CVICHE_SESSION_SECRET: "VAR_SESSION_SECRET"
      
      
patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: sa-patch.yaml
  - path: ingress-patch.yaml