apiVersion: v1
kind: ServiceAccount
metadata:
  name: cviche-sa
  annotations:
    # Use this exact placeholder
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID_PLACEHOLDER:role/cviche-bedrock-role
    
    